AWSTemplateFormatVersion: 2010-09-09
Description:  Configures a new CloudTrail Trail, S3 Bucket and CloudWatch Log Group and adds a Subscription Filter to CloudWatch Logs Destination.

Parameters:

  SentryAWSAccount:
    Type: String
    Description: The AWS Account that will recieve the CloudTrail Events
    Default: LogDestinationAccountNo

  LogDestinationName:
    Type: String
    Description: The name of the CloudWatch Logs Destination in the Receiving AWS Account
    Default: CrossAccountLogStreamingDestination

Resources:

  CloudTrailS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cloudtrail-bucket-${AWS::AccountId}
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled

  # S3 Bucket used for CloudTrail Logs (required by CloudTrail)
  CloudTrailS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Action: 's3:GetBucketAcl'
            Resource: !Sub 'arn:aws:s3:::${CloudTrailS3Bucket}'
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${CloudTrailS3Bucket}/*'
            Condition:
              StringEquals:
                's3:x-amz-acl': 'bucket-owner-full-control'

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "CloudTrailLogGroup"
      RetentionInDays: 1

  # Role for allowing CLoudTrail to write to CloudWatch Logs
  CloudWatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AssumeRole
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: 'cloudtrail-policy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AWSCloudTrailCreateLogStream2014110
            Effect: Allow
            Action: 'logs:CreateLogStream'
            Resource: !GetAtt CloudWatchLogsGroup.Arn
          - Sid: AWSCloudTrailPutLogEvents20141101
            Effect: Allow
            Action: 'logs:PutLogEvents'
            Resource: !GetAtt CloudWatchLogsGroup.Arn


  # CloudTrail Trail for Sentry Permission Hunter
  CloudTrailAuditTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      CloudWatchLogsLogGroupArn: !GetAtt CloudWatchLogsGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudWatchRole.Arn
      EventSelectors:
        - DataResources:
          - Type: AWS::S3::Object
            Values:
              - 'arn:aws:s3:::'
          IncludeManagementEvents: True
          ReadWriteType: All
      IncludeGlobalServiceEvents: True
      IsLogging: True
      IsMultiRegionTrail: True
      S3BucketName: !Ref CloudTrailS3Bucket
      TrailName: StreamingLogDemo

  # Subscription to CloudWatch Log Group
  SubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: !Ref CloudWatchLogsGroup
      DestinationArn: !Sub arn:aws:logs:${AWS::Region}:${SentryAWSAccount}:destination:${LogDestinationName}
      FilterPattern: ""